<?php

namespace Facades;

/**
 * Method for Test Class.
 *
 * @method static string string()
 * @method static string abs()
 */
class TestFacade extends Facade
{
    /**
     * @return string
     */
    public static function setNameSpace(): string
    {
        return Test::class; // TODO: Change the autogenerated stub
    }
}
